no_metadata = true
# num_repeats = 8
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
max_train_epochs = 15
gradient_accumulation_steps = 1
gradient_checkpointing = false
huber_c = 0.05
huber_schedule = "snr"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
learning_rate = 0.0001
loss_type = "l2"
lr_scheduler = "cosine"
max_bucket_reso = 1024
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 128
min_bucket_reso = 256
min_snr_gamma = 7
mixed_precision = "bf16"
network_alpha = 16
network_dim = 16
network_module = "networks.lora"
network_args = ["conv_dim=4", "conv_alpha=4", "dropout=0.1"]
no_half_vae = true
noise_offset_type = "Original"
optimizer_type = "adamw"
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 3
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = 0.0001
train_batch_size = 4
train_data_dir = ""
training_comment = ""
unet_lr = 0.0001
xformers = true
shuffle_caption = true